FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY components.json ./components.json
COPY index.html ./index.html
COPY postcss.config.js ./postcss.config.js
COPY tailwind.config.ts ./tailwind.config.ts
COPY tsconfig.json ./tsconfig.json
COPY vite.config.ts ./vite.config.ts
COPY public ./public
COPY src ./src

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
