/* eslint-disable */

// This file is generated by packages/tooling/scripts/generate_contracts.py.

// Do not edit by hand.

export interface AcceptPinnedFactCandidateRequest {
  value_kind?: "text" | "json" | null;
  value_text?: string | null;
  value_json?: Record<string, unknown> | null;
  review_notes?: string | null;
}

export interface AdminEffectiveLimitsResponse {
  documents?: number | null;
  max_file_size_bytes?: number | null;
  chunks?: number | null;
  storage_bytes?: number | null;
  tokens_5h?: number | null;
  tokens_week?: number | null;
  retrieval_chunks: number;
  output_tokens: number;
  per_document_chunks: number;
}

export interface AdminManagedUserListResponse {
  items: Array<AdminManagedUserResponse>;
  total: number;
  page: number;
  page_size: number;
}

export interface AdminManagedUserResponse {
  id: string;
  email: string;
  full_name?: string | null;
  is_active: boolean;
  is_admin: boolean;
  must_change_password: boolean;
  last_login?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AdminUpdateUserRequest {
  is_active?: boolean | null;
  is_admin?: boolean | null;
  must_change_password?: boolean | null;
}

export interface BatchDocumentStatusRequest {
  document_ids?: Array<string>;
}

export interface BatchDocumentStatusResponse {
  statuses: Array<DocumentProcessingStatusResponse>;
}

export interface Body_create_upload_api_v1_ingestion_uploads_post {
  file: Blob;
}

export interface ChangeEventDetail {
  id: string;
  space_id: string;
  event_type: string;
  title: string;
  summary: string;
  document_id?: string | null;
  pinned_fact_id?: string | null;
  correction_id?: string | null;
  chat_session_id?: string | null;
  created_at: string;
  is_read?: boolean;
  payload?: Record<string, unknown> | null;
}

export interface ChangeEventReadResult {
  change_event_id: string;
  read_at: string;
}

export interface ChangeEventSummary {
  id: string;
  space_id: string;
  event_type: string;
  title: string;
  summary: string;
  document_id?: string | null;
  pinned_fact_id?: string | null;
  correction_id?: string | null;
  chat_session_id?: string | null;
  created_at: string;
  is_read?: boolean;
}

export interface ChangeListResponse {
  items: Array<ChangeEventSummary>;
  total: number;
  page: number;
  page_size: number;
}

export interface ChatEvidenceRecord {
  id: string;
  source_type: string;
  source_tier: SourceTier;
  text: string;
  citations?: Array<Citation>;
  score?: number | null;
  title?: string | null;
  created_at?: string | null;
}

export interface ChatMessageRecord {
  id: string;
  role: string;
  content: string;
  citations?: Array<Citation>;
  suggestions?: Array<ChatSuggestion>;
  evidence?: Array<ChatEvidenceRecord>;
  retrieval_mode?: string | null;
  degraded?: boolean;
  created_at: string;
}

export interface ChatSendMessageRequest {
  content: string;
}

export interface ChatSendMessageResponse {
  session: ChatSessionDetail;
  user_message: ChatMessageRecord;
  assistant_message: ChatMessageRecord;
}

export interface ChatSessionDetail {
  id: string;
  space_id: string;
  document_id?: string | null;
  title: string;
  message_count: number;
  last_message_at?: string | null;
  created_at: string;
  updated_at: string;
  messages?: Array<ChatMessageRecord>;
}

export interface ChatSessionListResponse {
  items: Array<ChatSessionSummary>;
  total: number;
  page: number;
  page_size: number;
}

export interface ChatSessionSummary {
  id: string;
  space_id: string;
  document_id?: string | null;
  title: string;
  message_count: number;
  last_message_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface ChatSuggestion {
  label: string;
  prompt: string;
}

export interface Citation {
  document_id?: string | null;
  entity_id?: string | null;
  chunk_id?: string | null;
  title?: string | null;
  locator?: string | null;
  line_number?: number | null;
  source_tier?: SourceTier;
}

export interface CorrectionCreateRequest {
  pinned_fact_id?: string | null;
  chat_session_id?: string | null;
  chat_message_id?: string | null;
  document_id?: string | null;
  entity_id?: string | null;
  locator_text?: string | null;
  proposed_value: string;
  rationale?: string | null;
}

export interface CorrectionListResponse {
  items: Array<CorrectionRecordResponse>;
  total: number;
  page: number;
  page_size: number;
}

export interface CorrectionRecordResponse {
  id: string;
  space_id: string;
  submitted_by: string;
  chat_session_id?: string | null;
  chat_message_id?: string | null;
  pinned_fact_id?: string | null;
  document_id?: string | null;
  entity_id?: string | null;
  locator_text?: string | null;
  proposed_value: string;
  rationale?: string | null;
  status: string;
  review_notes?: string | null;
  reviewed_by?: string | null;
  reviewed_at?: string | null;
  created_at: string;
  updated_at: string;
  citation: Citation;
}

export interface CorrectionReviewRequest {
  review_notes?: string | null;
}

export interface DependencyStatus {
  status?: string;
  detail?: string;
  backend?: string | null;
}

export interface DocumentDetail {
  id: string;
  space_id: string;
  uploaded_by: string;
  title: string;
  original_filename: string;
  mime_type: string;
  file_type: string;
  file_size: number;
  source_kind: "manual_upload" | "external_sync";
  source_label?: string | null;
  processing_status: ProcessingStatus;
  chunk_count: number;
  indexed_chunk_count: number;
  created_at: string;
  updated_at: string;
  preview_text?: string | null;
  original_text_content?: string | null;
}

export interface DocumentListItem {
  id: string;
  space_id: string;
  uploaded_by: string;
  title: string;
  original_filename: string;
  mime_type: string;
  file_type: string;
  file_size: number;
  source_kind: "manual_upload" | "external_sync";
  source_label?: string | null;
  processing_status: ProcessingStatus;
  chunk_count: number;
  indexed_chunk_count: number;
  created_at: string;
  updated_at: string;
}

export interface DocumentListResponse {
  items: Array<DocumentListItem>;
  total: number;
  page: number;
  page_size: number;
}

export interface DocumentProcessingJobResponse {
  id: string;
  requested_stage: string;
  status: string;
  attempt: number;
  visible_error_detail?: string | null;
  queued_at: string;
  started_at?: string | null;
  completed_at?: string | null;
}

export interface DocumentProcessingStatusResponse {
  document_id: string;
  space_id: string;
  uploaded_by: string;
  processing_status: ProcessingStatus;
  chunk_count: number;
  indexed_chunk_count: number;
  latest_job?: DocumentProcessingJobResponse | null;
  active_job?: DocumentProcessingJobResponse | null;
  queue_runtime?: DocumentQueueRuntimeResponse | null;
  queued_job_count?: number;
  has_queued_reprocess?: boolean;
  updated_at: string;
}

export interface DocumentQueueRuntimeResponse {
  job_id: string;
  queue_job_id: string;
  queue_name: string;
  status: string;
  stage?: string | null;
  detail?: string | null;
  worker_name?: string | null;
  queue_position?: number | null;
  chunk_progress_current?: number;
  chunk_progress_total?: number;
  enqueued_at?: string | null;
  started_at?: string | null;
  ended_at?: string | null;
  updated_at?: string | null;
}

export interface DocumentUpdateRequest {
  space_id: string;
}

export interface EntityDetailResponse {
  id: string;
  space_id: string;
  entity_type: string;
  display_name: string;
  normalized_name: string;
  graph_node_id?: string | null;
  mention_count: number;
  document_count: number;
  latest_mentioned_at?: string | null;
  created_at: string;
  updated_at: string;
  provenance?: Array<EntityMentionRecord>;
  history?: Array<EntityHistoryEntry>;
  related_documents?: Array<EntityRelatedDocument>;
}

export interface EntityHistoryEntry {
  mention_id: string;
  document_id: string;
  surface_text: string;
  observed_at: string;
  citation: Citation;
}

export interface EntityListItem {
  id: string;
  space_id: string;
  entity_type: string;
  display_name: string;
  normalized_name: string;
  graph_node_id?: string | null;
  mention_count: number;
  document_count: number;
  latest_mentioned_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface EntityListResponse {
  items: Array<EntityListItem>;
  total: number;
  page: number;
  page_size: number;
}

export interface EntityMentionRecord {
  mention_id: string;
  document_id: string;
  chunk_id: string;
  surface_text: string;
  normalized_name: string;
  confidence_score?: number | null;
  extraction_metadata?: Record<string, unknown> | null;
  created_at: string;
  citation: Citation;
}

export interface EntityRelatedDocument {
  document_id: string;
  title: string;
  file_type: string;
  mention_count: number;
  latest_mentioned_at?: string | null;
  citation?: Citation | null;
}

export interface GraphLinkResponse {
  source_id: string;
  target_id: string;
  relation_type: string;
  weight: number;
  citations?: Array<Citation>;
}

export interface GraphNodeResponse {
  id: string;
  space_id: string;
  label: string;
  node_type: string;
}

export interface GraphResponse {
  seed_entity_id?: string | null;
  document_id?: string | null;
  depth: number;
  nodes?: Array<GraphNodeResponse>;
  links?: Array<GraphLinkResponse>;
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}

export interface HealthStatusResponse {
  status?: string;
  services: Record<string, DependencyStatus>;
}

export interface LivenessResponse {
  status?: string;
}

export interface LoginTokenResponse {
  access_token: string;
  token_type?: string;
  must_change_password?: boolean;
}

export interface MutationResult {
  success?: boolean;
  message?: string | null;
}

export interface PinnedFactActor {
  id: string;
  email: string;
  full_name?: string | null;
}

export interface PinnedFactCandidate {
  id: string;
  pinned_fact_id: string;
  space_id: string;
  source_document_id?: string | null;
  proposed_value_kind: "text" | "json";
  proposed_value_text?: string | null;
  proposed_value_json?: Record<string, unknown> | null;
  change_type: "same" | "update" | "evidence_update" | "conflict" | "unknown";
  confidence?: number | null;
  evidence?: Array<PinnedFactEvidenceOutput>;
  status: "pending" | "accepted" | "rejected" | "auto_applied";
  review_notes?: string | null;
  reviewed_by?: string | null;
  reviewed_at?: string | null;
  created_at: string;
}

export interface PinnedFactCandidateListResponse {
  items: Array<PinnedFactCandidate>;
}

export interface PinnedFactCreateRequest {
  value_kind: "text" | "json";
  value_text?: string | null;
  value_json?: Record<string, unknown> | null;
  key: string;
  title: string;
  description: string;
  entity_type_hint?: string | null;
  is_active?: boolean;
  confidence?: number | null;
  source_document_id?: string | null;
  evidence: Array<PinnedFactEvidenceInput>;
}

export interface PinnedFactDetail {
  id: string;
  space_id: string;
  key: string;
  title: string;
  description: string;
  entity_type_hint?: string | null;
  is_active: boolean;
  status: "active" | "pending_update" | "conflicted" | "missing_evidence" | "unknown";
  confidence?: number | null;
  value_kind?: "text" | "json" | null;
  value_text?: string | null;
  value_json?: Record<string, unknown> | null;
  source_document_id?: string | null;
  evidence?: Array<PinnedFactEvidenceOutput>;
  last_checked_at?: string | null;
  pending_candidate_count?: number;
  conflict_count?: number;
  created_by?: PinnedFactActor | null;
  updated_by?: PinnedFactActor | null;
  created_at: string;
  updated_at: string;
  history_count?: number;
}

export interface PinnedFactDetectionPreviewRequest {
  description: string;
  entity_type_hint?: string | null;
}

export interface PinnedFactDetectionPreviewResponse {
  assistant_message: ChatMessageRecord;
  retrieval_results?: Array<SearchResult>;
  source_document_id?: string | null;
}

export interface PinnedFactEvidenceInput {
  quote: string;
  citations?: Array<Citation>;
  source_chunk_ids?: Array<string>;
}

export interface PinnedFactEvidenceOutput {
  quote: string;
  citations?: Array<Citation>;
  source_chunk_ids?: Array<string>;
}

export interface PinnedFactHistoryEntry {
  id: string;
  pinned_fact_id: string;
  candidate_id?: string | null;
  restored_from_history_id?: string | null;
  actor_user_id?: string | null;
  actor_type: string;
  reason: string;
  old_value_kind?: "text" | "json" | null;
  old_value_text?: string | null;
  old_value_json?: Record<string, unknown> | null;
  new_value_kind: "text" | "json";
  new_value_text?: string | null;
  new_value_json?: Record<string, unknown> | null;
  old_evidence?: Array<PinnedFactEvidenceOutput>;
  new_evidence?: Array<PinnedFactEvidenceOutput>;
  update_note?: string | null;
  created_at: string;
}

export interface PinnedFactHistoryResponse {
  items: Array<PinnedFactHistoryEntry>;
}

export interface PinnedFactListResponse {
  items: Array<PinnedFactSummary>;
  total: number;
  page: number;
  page_size: number;
}

export interface PinnedFactSummary {
  id: string;
  space_id: string;
  key: string;
  title: string;
  description: string;
  entity_type_hint?: string | null;
  is_active: boolean;
  status: "active" | "pending_update" | "conflicted" | "missing_evidence" | "unknown";
  confidence?: number | null;
  value_kind?: "text" | "json" | null;
  value_text?: string | null;
  value_json?: Record<string, unknown> | null;
  source_document_id?: string | null;
  evidence?: Array<PinnedFactEvidenceOutput>;
  last_checked_at?: string | null;
  pending_candidate_count?: number;
  conflict_count?: number;
  created_by?: PinnedFactActor | null;
  updated_by?: PinnedFactActor | null;
  created_at: string;
  updated_at: string;
}

export interface PinnedFactUpdateRequest {
  title?: string | null;
  description?: string | null;
  entity_type_hint?: string | null;
  is_active?: boolean | null;
  value_kind?: "text" | "json" | null;
  value_text?: string | null;
  value_json?: Record<string, unknown> | null;
  confidence?: number | null;
  source_document_id?: string | null;
  evidence?: Array<PinnedFactEvidenceInput> | null;
  update_note?: string | null;
}

export interface ProblemResponse {
  type?: string;
  title?: string;
  status: number;
  detail: string;
  instance?: string;
  code?: string | null;
}

export type ProcessingStageStatus = "pending" | "processing" | "completed" | "failed" | "deferred";

export interface ProcessingStatus {
  overall?: ProcessingStageStatus;
  upload?: ProcessingStageStatus;
  parsing?: ProcessingStageStatus;
  vector?: ProcessingStageStatus;
  extraction?: ProcessingStageStatus;
  graph?: ProcessingStageStatus;
  detail?: string | null;
}

export interface RegisterRequest {
  email: string;
  password: string;
  full_name?: string | null;
}

export interface RejectPinnedFactCandidateRequest {
  review_notes?: string | null;
}

export interface SearchEntitySummary {
  id: string;
  entity_type: string;
  display_name: string;
  normalized_name: string;
  mention_count?: number | null;
}

export type SearchMode = "boolean" | "vector" | "graph" | "combined";

export interface SearchResponse {
  items: Array<SearchResult>;
  total: number;
  page: number;
  page_size: number;
}

export interface SearchResult {
  result_id: string;
  result_kind: "document_chunk" | "entity";
  score: number;
  matched_modes?: Array<SearchMode>;
  document?: SearchResultDocument | null;
  preview_text: string;
  entity?: SearchEntitySummary | null;
  citations?: Array<Citation>;
}

export interface SearchResultDocument {
  id: string;
  space_id: string;
  title: string;
  file_type: string;
  created_at: string;
}

export type SourceTier = "document" | "derived" | "user" | "verified";

export interface SpaceCreateRequest {
  name: string;
  description?: string | null;
}

export interface SpaceListResponse {
  items: Array<SpaceResponse>;
}

export interface SpaceResponse {
  id: string;
  owner_user_id: string;
  name: string;
  description?: string | null;
  is_default: boolean;
  document_count: number;
  pinned_fact_count: number;
  archived_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface SpaceUpdateRequest {
  name?: string | null;
  description?: string | null;
  archived?: boolean | null;
  is_default?: boolean | null;
}

export interface UpdateCurrentUserRequest {
  full_name?: string | null;
  email?: string | null;
  current_password?: string | null;
  new_password?: string | null;
}

export interface UploadDocumentResponse {
  document_id: string;
  job_id: string;
  filename: string;
  processing_status: ProcessingStatus;
}

export interface UsageAmounts {
  documents?: number;
  chunks?: number;
  storage_bytes?: number;
  tokens_5h?: number;
  tokens_week?: number;
}

export interface UsageLimitSet {
  documents?: number | null;
  max_file_size_bytes?: number | null;
  chunks?: number | null;
  storage_bytes?: number | null;
  tokens_5h?: number | null;
  tokens_week?: number | null;
  retrieval_chunks?: number | null;
  output_tokens?: number | null;
  per_document_chunks?: number | null;
}

export interface UsagePercentages {
  documents?: number | null;
  chunks?: number | null;
  storage_bytes?: number | null;
  tokens_5h?: number | null;
  tokens_week?: number | null;
}

export interface UsageResetTimers {
  tokens_5h_resets_at?: string | null;
  tokens_week_resets_at?: string | null;
}

export interface UsageStatusFlags {
  chat_blocked?: boolean;
  upload_blocked?: boolean;
  partially_indexed_documents?: number;
}

export interface UsageSummaryResponse {
  usage: UsageAmounts;
  limits: UsageLimitSet;
  percent_used: UsagePercentages;
  resets_at: UsageResetTimers;
  status: UsageStatusFlags;
}

export interface UserProfileResponse {
  id: string;
  email: string;
  full_name?: string | null;
  is_active: boolean;
  is_admin?: boolean;
  must_change_password?: boolean;
  last_login?: string | null;
}

export interface ValidationError {
  loc: Array<string | number>;
  msg: string;
  type: string;
}

export interface ApiOperations {
  "read_effective_limits_api_v1_admin_effective_limits_get": ReadEffectiveLimitsApiV1AdminEffectiveLimitsGetOperation;
  "read_managed_users_api_v1_admin_users_get": ReadManagedUsersApiV1AdminUsersGetOperation;
  "read_managed_user_api_v1_admin_users__user_id__get": ReadManagedUserApiV1AdminUsersUserIdGetOperation;
  "patch_managed_user_api_v1_admin_users__user_id__patch": PatchManagedUserApiV1AdminUsersUserIdPatchOperation;
  "login_api_v1_auth_login_post": LoginApiV1AuthLoginPostOperation;
  "read_current_user_api_v1_auth_me_get": ReadCurrentUserApiV1AuthMeGetOperation;
  "patch_current_user_api_v1_auth_me_patch": PatchCurrentUserApiV1AuthMePatchOperation;
  "register_api_v1_auth_register_post": RegisterApiV1AuthRegisterPostOperation;
  "read_changes_api_v1_changes_get": ReadChangesApiV1ChangesGetOperation;
  "read_change_detail_api_v1_changes__change_id__get": ReadChangeDetailApiV1ChangesChangeIdGetOperation;
  "read_change_api_v1_changes__change_id__read_post": ReadChangeApiV1ChangesChangeIdReadPostOperation;
  "read_chat_sessions_api_v1_chat_sessions_get": ReadChatSessionsApiV1ChatSessionsGetOperation;
  "post_chat_session_api_v1_chat_sessions_post": PostChatSessionApiV1ChatSessionsPostOperation;
  "read_chat_session_detail_api_v1_chat_sessions__session_id__get": ReadChatSessionDetailApiV1ChatSessionsSessionIdGetOperation;
  "post_chat_message_api_v1_chat_sessions__session_id__messages_post": PostChatMessageApiV1ChatSessionsSessionIdMessagesPostOperation;
  "read_corrections_api_v1_corrections_get": ReadCorrectionsApiV1CorrectionsGetOperation;
  "post_correction_api_v1_corrections_post": PostCorrectionApiV1CorrectionsPostOperation;
  "read_correction_detail_api_v1_corrections__correction_id__get": ReadCorrectionDetailApiV1CorrectionsCorrectionIdGetOperation;
  "reject_correction_api_v1_corrections__correction_id__reject_post": RejectCorrectionApiV1CorrectionsCorrectionIdRejectPostOperation;
  "verify_correction_api_v1_corrections__correction_id__verify_post": VerifyCorrectionApiV1CorrectionsCorrectionIdVerifyPostOperation;
  "read_documents_api_v1_documents_get": ReadDocumentsApiV1DocumentsGetOperation;
  "delete_document_route_api_v1_documents__document_id__delete": DeleteDocumentRouteApiV1DocumentsDocumentIdDeleteOperation;
  "read_document_api_v1_documents__document_id__get": ReadDocumentApiV1DocumentsDocumentIdGetOperation;
  "patch_document_api_v1_documents__document_id__patch": PatchDocumentApiV1DocumentsDocumentIdPatchOperation;
  "download_document_api_v1_documents__document_id__download_get": DownloadDocumentApiV1DocumentsDocumentIdDownloadGetOperation;
  "read_entities_api_v1_entities_get": ReadEntitiesApiV1EntitiesGetOperation;
  "read_entity_detail_api_v1_entities__entity_id__get": ReadEntityDetailApiV1EntitiesEntityIdGetOperation;
  "health_readiness_api_v1_health_get": HealthReadinessApiV1HealthGetOperation;
  "read_batch_document_status_api_v1_ingestion_documents_status_batch_post": ReadBatchDocumentStatusApiV1IngestionDocumentsStatusBatchPostOperation;
  "reprocess_document_api_v1_ingestion_documents__document_id__reprocess_post": ReprocessDocumentApiV1IngestionDocumentsDocumentIdReprocessPostOperation;
  "retry_extraction_api_v1_ingestion_documents__document_id__retry_extraction_post": RetryExtractionApiV1IngestionDocumentsDocumentIdRetryExtractionPostOperation;
  "retry_graph_api_v1_ingestion_documents__document_id__retry_graph_post": RetryGraphApiV1IngestionDocumentsDocumentIdRetryGraphPostOperation;
  "retry_parsing_api_v1_ingestion_documents__document_id__retry_parsing_post": RetryParsingApiV1IngestionDocumentsDocumentIdRetryParsingPostOperation;
  "retry_vector_api_v1_ingestion_documents__document_id__retry_vector_post": RetryVectorApiV1IngestionDocumentsDocumentIdRetryVectorPostOperation;
  "read_document_status_api_v1_ingestion_documents__document_id__status_get": ReadDocumentStatusApiV1IngestionDocumentsDocumentIdStatusGetOperation;
  "create_upload_api_v1_ingestion_uploads_post": CreateUploadApiV1IngestionUploadsPostOperation;
  "read_document_graph_api_v1_knowledge_graph_documents__document_id__get": ReadDocumentGraphApiV1KnowledgeGraphDocumentsDocumentIdGetOperation;
  "read_entity_subgraph_api_v1_knowledge_graph_entities__entity_id__subgraph_get": ReadEntitySubgraphApiV1KnowledgeGraphEntitiesEntityIdSubgraphGetOperation;
  "read_pinned_facts_api_v1_pinned_facts_get": ReadPinnedFactsApiV1PinnedFactsGetOperation;
  "post_pinned_fact_api_v1_pinned_facts_post": PostPinnedFactApiV1PinnedFactsPostOperation;
  "read_pinned_fact_candidate_detail_api_v1_pinned_facts_candidates__candidate_id__get": ReadPinnedFactCandidateDetailApiV1PinnedFactsCandidatesCandidateIdGetOperation;
  "post_accept_pinned_fact_candidate_api_v1_pinned_facts_candidates__candidate_id__accept_post": PostAcceptPinnedFactCandidateApiV1PinnedFactsCandidatesCandidateIdAcceptPostOperation;
  "post_reject_pinned_fact_candidate_api_v1_pinned_facts_candidates__candidate_id__reject_post": PostRejectPinnedFactCandidateApiV1PinnedFactsCandidatesCandidateIdRejectPostOperation;
  "post_pinned_fact_detect_preview_api_v1_pinned_facts_detect_preview_post": PostPinnedFactDetectPreviewApiV1PinnedFactsDetectPreviewPostOperation;
  "read_pinned_fact_detail_api_v1_pinned_facts__fact_id__get": ReadPinnedFactDetailApiV1PinnedFactsFactIdGetOperation;
  "patch_pinned_fact_api_v1_pinned_facts__fact_id__patch": PatchPinnedFactApiV1PinnedFactsFactIdPatchOperation;
  "read_pinned_fact_candidates_api_v1_pinned_facts__fact_id__candidates_get": ReadPinnedFactCandidatesApiV1PinnedFactsFactIdCandidatesGetOperation;
  "read_pinned_fact_history_api_v1_pinned_facts__fact_id__history_get": ReadPinnedFactHistoryApiV1PinnedFactsFactIdHistoryGetOperation;
  "post_revert_pinned_fact_history_api_v1_pinned_facts__fact_id__history__history_id__revert_post": PostRevertPinnedFactHistoryApiV1PinnedFactsFactIdHistoryHistoryIdRevertPostOperation;
  "post_recheck_pinned_fact_api_v1_pinned_facts__fact_id__recheck_post": PostRecheckPinnedFactApiV1PinnedFactsFactIdRecheckPostOperation;
  "read_search_results_api_v1_search_get": ReadSearchResultsApiV1SearchGetOperation;
  "read_spaces_api_v1_spaces_get": ReadSpacesApiV1SpacesGetOperation;
  "post_space_api_v1_spaces_post": PostSpaceApiV1SpacesPostOperation;
  "delete_space_api_v1_spaces__space_id__delete": DeleteSpaceApiV1SpacesSpaceIdDeleteOperation;
  "read_space_api_v1_spaces__space_id__get": ReadSpaceApiV1SpacesSpaceIdGetOperation;
  "patch_space_api_v1_spaces__space_id__patch": PatchSpaceApiV1SpacesSpaceIdPatchOperation;
  "read_my_usage_api_v1_usage_me_get": ReadMyUsageApiV1UsageMeGetOperation;
  "health_liveness_health_get": HealthLivenessHealthGetOperation;
  "runtime_status_status_get": RuntimeStatusStatusGetOperation;
}

export interface ReadEffectiveLimitsApiV1AdminEffectiveLimitsGetOperation {
  method: "get";
  path: "/api/v1/admin/effective-limits";
  pathParams: never;
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: AdminEffectiveLimitsResponse;
  401: ProblemResponse;
  403: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: AdminEffectiveLimitsResponse;
}

export interface ReadManagedUsersApiV1AdminUsersGetOperation {
  method: "get";
  path: "/api/v1/admin/users";
  pathParams: never;
  queryParams: {
  page?: number;
  page_size?: number;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: AdminManagedUserListResponse;
  401: ProblemResponse;
  403: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: AdminManagedUserListResponse;
}

export interface ReadManagedUserApiV1AdminUsersUserIdGetOperation {
  method: "get";
  path: "/api/v1/admin/users/{user_id}";
  pathParams: {
  user_id: string;
};
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: AdminManagedUserResponse;
  401: ProblemResponse;
  403: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: AdminManagedUserResponse;
}

export interface PatchManagedUserApiV1AdminUsersUserIdPatchOperation {
  method: "patch";
  path: "/api/v1/admin/users/{user_id}";
  pathParams: {
  user_id: string;
};
  queryParams: never;
  requestBody: AdminUpdateUserRequest;
  requestContentType: "application/json";
  responses: {
  200: AdminManagedUserResponse;
  401: ProblemResponse;
  403: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: AdminManagedUserResponse;
}

export interface LoginApiV1AuthLoginPostOperation {
  method: "post";
  path: "/api/v1/auth/login";
  pathParams: never;
  queryParams: never;
  requestBody: {
  username: string;
  password: string;
};
  requestContentType: "application/x-www-form-urlencoded";
  responses: {
  200: LoginTokenResponse;
  401: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: LoginTokenResponse;
}

export interface ReadCurrentUserApiV1AuthMeGetOperation {
  method: "get";
  path: "/api/v1/auth/me";
  pathParams: never;
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: UserProfileResponse;
  401: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: UserProfileResponse;
}

export interface PatchCurrentUserApiV1AuthMePatchOperation {
  method: "patch";
  path: "/api/v1/auth/me";
  pathParams: never;
  queryParams: never;
  requestBody: UpdateCurrentUserRequest;
  requestContentType: "application/json";
  responses: {
  200: UserProfileResponse;
  401: ProblemResponse;
  409: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: UserProfileResponse;
}

export interface RegisterApiV1AuthRegisterPostOperation {
  method: "post";
  path: "/api/v1/auth/register";
  pathParams: never;
  queryParams: never;
  requestBody: RegisterRequest;
  requestContentType: "application/json";
  responses: {
  201: UserProfileResponse;
  401: ProblemResponse;
  409: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: UserProfileResponse;
}

export interface ReadChangesApiV1ChangesGetOperation {
  method: "get";
  path: "/api/v1/changes";
  pathParams: never;
  queryParams: {
  page?: number;
  page_size?: number;
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: ChangeListResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: ChangeListResponse;
}

export interface ReadChangeDetailApiV1ChangesChangeIdGetOperation {
  method: "get";
  path: "/api/v1/changes/{change_id}";
  pathParams: {
  change_id: string;
};
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: ChangeEventDetail;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: ChangeEventDetail;
}

export interface ReadChangeApiV1ChangesChangeIdReadPostOperation {
  method: "post";
  path: "/api/v1/changes/{change_id}/read";
  pathParams: {
  change_id: string;
};
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: ChangeEventReadResult;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: ChangeEventReadResult;
}

export interface ReadChatSessionsApiV1ChatSessionsGetOperation {
  method: "get";
  path: "/api/v1/chat/sessions";
  pathParams: never;
  queryParams: {
  page?: number;
  page_size?: number;
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: ChatSessionListResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: ChatSessionListResponse;
}

export interface PostChatSessionApiV1ChatSessionsPostOperation {
  method: "post";
  path: "/api/v1/chat/sessions";
  pathParams: never;
  queryParams: {
  document_id?: string | null;
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: ChatSessionSummary;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: ChatSessionSummary;
}

export interface ReadChatSessionDetailApiV1ChatSessionsSessionIdGetOperation {
  method: "get";
  path: "/api/v1/chat/sessions/{session_id}";
  pathParams: {
  session_id: string;
};
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: ChatSessionDetail;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: ChatSessionDetail;
}

export interface PostChatMessageApiV1ChatSessionsSessionIdMessagesPostOperation {
  method: "post";
  path: "/api/v1/chat/sessions/{session_id}/messages";
  pathParams: {
  session_id: string;
};
  queryParams: never;
  requestBody: ChatSendMessageRequest;
  requestContentType: "application/json";
  responses: {
  200: ChatSendMessageResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: ChatSendMessageResponse;
}

export interface ReadCorrectionsApiV1CorrectionsGetOperation {
  method: "get";
  path: "/api/v1/corrections";
  pathParams: never;
  queryParams: {
  status?: string | null;
  page?: number;
  page_size?: number;
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: CorrectionListResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: CorrectionListResponse;
}

export interface PostCorrectionApiV1CorrectionsPostOperation {
  method: "post";
  path: "/api/v1/corrections";
  pathParams: never;
  queryParams: {
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: CorrectionCreateRequest;
  requestContentType: "application/json";
  responses: {
  200: CorrectionRecordResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: CorrectionRecordResponse;
}

export interface ReadCorrectionDetailApiV1CorrectionsCorrectionIdGetOperation {
  method: "get";
  path: "/api/v1/corrections/{correction_id}";
  pathParams: {
  correction_id: string;
};
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: CorrectionRecordResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: CorrectionRecordResponse;
}

export interface RejectCorrectionApiV1CorrectionsCorrectionIdRejectPostOperation {
  method: "post";
  path: "/api/v1/corrections/{correction_id}/reject";
  pathParams: {
  correction_id: string;
};
  queryParams: never;
  requestBody: CorrectionReviewRequest;
  requestContentType: "application/json";
  responses: {
  200: CorrectionRecordResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: CorrectionRecordResponse;
}

export interface VerifyCorrectionApiV1CorrectionsCorrectionIdVerifyPostOperation {
  method: "post";
  path: "/api/v1/corrections/{correction_id}/verify";
  pathParams: {
  correction_id: string;
};
  queryParams: never;
  requestBody: CorrectionReviewRequest;
  requestContentType: "application/json";
  responses: {
  200: CorrectionRecordResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: CorrectionRecordResponse;
}

export interface ReadDocumentsApiV1DocumentsGetOperation {
  method: "get";
  path: "/api/v1/documents";
  pathParams: never;
  queryParams: {
  date_from?: string | null;
  date_to?: string | null;
  file_type?: string | null;
  uploaded_by?: string | null;
  page?: number;
  page_size?: number;
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: DocumentListResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  409: ProblemResponse;
  422: ProblemResponse;
  503: ProblemResponse;
};
  successResponse: DocumentListResponse;
}

export interface DeleteDocumentRouteApiV1DocumentsDocumentIdDeleteOperation {
  method: "delete";
  path: "/api/v1/documents/{document_id}";
  pathParams: {
  document_id: string;
};
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: MutationResult;
  401: ProblemResponse;
  404: ProblemResponse;
  409: ProblemResponse;
  422: ProblemResponse;
  503: ProblemResponse;
};
  successResponse: MutationResult;
}

export interface ReadDocumentApiV1DocumentsDocumentIdGetOperation {
  method: "get";
  path: "/api/v1/documents/{document_id}";
  pathParams: {
  document_id: string;
};
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: DocumentDetail;
  401: ProblemResponse;
  404: ProblemResponse;
  409: ProblemResponse;
  422: ProblemResponse;
  503: ProblemResponse;
};
  successResponse: DocumentDetail;
}

export interface PatchDocumentApiV1DocumentsDocumentIdPatchOperation {
  method: "patch";
  path: "/api/v1/documents/{document_id}";
  pathParams: {
  document_id: string;
};
  queryParams: never;
  requestBody: DocumentUpdateRequest;
  requestContentType: "application/json";
  responses: {
  200: DocumentDetail;
  401: ProblemResponse;
  404: ProblemResponse;
  409: ProblemResponse;
  422: ProblemResponse;
  503: ProblemResponse;
};
  successResponse: DocumentDetail;
}

export interface DownloadDocumentApiV1DocumentsDocumentIdDownloadGetOperation {
  method: "get";
  path: "/api/v1/documents/{document_id}/download";
  pathParams: {
  document_id: string;
};
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: unknown;
  401: ProblemResponse;
  404: ProblemResponse;
  409: ProblemResponse;
  422: ProblemResponse;
  503: ProblemResponse;
};
  successResponse: unknown;
}

export interface ReadEntitiesApiV1EntitiesGetOperation {
  method: "get";
  path: "/api/v1/entities";
  pathParams: never;
  queryParams: {
  q?: string | null;
  entity_type?: string | null;
  page?: number;
  page_size?: number;
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: EntityListResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: EntityListResponse;
}

export interface ReadEntityDetailApiV1EntitiesEntityIdGetOperation {
  method: "get";
  path: "/api/v1/entities/{entity_id}";
  pathParams: {
  entity_id: string;
};
  queryParams: {
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: EntityDetailResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: EntityDetailResponse;
}

export interface HealthReadinessApiV1HealthGetOperation {
  method: "get";
  path: "/api/v1/health";
  pathParams: never;
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: HealthStatusResponse;
};
  successResponse: HealthStatusResponse;
}

export interface ReadBatchDocumentStatusApiV1IngestionDocumentsStatusBatchPostOperation {
  method: "post";
  path: "/api/v1/ingestion/documents/status/batch";
  pathParams: never;
  queryParams: never;
  requestBody: BatchDocumentStatusRequest;
  requestContentType: "application/json";
  responses: {
  200: BatchDocumentStatusResponse;
  400: ProblemResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  409: ProblemResponse;
  413: ProblemResponse;
  422: ProblemResponse;
  429: ProblemResponse;
  503: ProblemResponse;
};
  successResponse: BatchDocumentStatusResponse;
}

export interface ReprocessDocumentApiV1IngestionDocumentsDocumentIdReprocessPostOperation {
  method: "post";
  path: "/api/v1/ingestion/documents/{document_id}/reprocess";
  pathParams: {
  document_id: string;
};
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: DocumentProcessingStatusResponse;
  400: ProblemResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  409: ProblemResponse;
  413: ProblemResponse;
  422: ProblemResponse;
  429: ProblemResponse;
  503: ProblemResponse;
};
  successResponse: DocumentProcessingStatusResponse;
}

export interface RetryExtractionApiV1IngestionDocumentsDocumentIdRetryExtractionPostOperation {
  method: "post";
  path: "/api/v1/ingestion/documents/{document_id}/retry/extraction";
  pathParams: {
  document_id: string;
};
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: DocumentProcessingStatusResponse;
  400: ProblemResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  409: ProblemResponse;
  413: ProblemResponse;
  422: ProblemResponse;
  429: ProblemResponse;
  503: ProblemResponse;
};
  successResponse: DocumentProcessingStatusResponse;
}

export interface RetryGraphApiV1IngestionDocumentsDocumentIdRetryGraphPostOperation {
  method: "post";
  path: "/api/v1/ingestion/documents/{document_id}/retry/graph";
  pathParams: {
  document_id: string;
};
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: DocumentProcessingStatusResponse;
  400: ProblemResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  409: ProblemResponse;
  413: ProblemResponse;
  422: ProblemResponse;
  429: ProblemResponse;
  503: ProblemResponse;
};
  successResponse: DocumentProcessingStatusResponse;
}

export interface RetryParsingApiV1IngestionDocumentsDocumentIdRetryParsingPostOperation {
  method: "post";
  path: "/api/v1/ingestion/documents/{document_id}/retry/parsing";
  pathParams: {
  document_id: string;
};
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: DocumentProcessingStatusResponse;
  400: ProblemResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  409: ProblemResponse;
  413: ProblemResponse;
  422: ProblemResponse;
  429: ProblemResponse;
  503: ProblemResponse;
};
  successResponse: DocumentProcessingStatusResponse;
}

export interface RetryVectorApiV1IngestionDocumentsDocumentIdRetryVectorPostOperation {
  method: "post";
  path: "/api/v1/ingestion/documents/{document_id}/retry/vector";
  pathParams: {
  document_id: string;
};
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: DocumentProcessingStatusResponse;
  400: ProblemResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  409: ProblemResponse;
  413: ProblemResponse;
  422: ProblemResponse;
  429: ProblemResponse;
  503: ProblemResponse;
};
  successResponse: DocumentProcessingStatusResponse;
}

export interface ReadDocumentStatusApiV1IngestionDocumentsDocumentIdStatusGetOperation {
  method: "get";
  path: "/api/v1/ingestion/documents/{document_id}/status";
  pathParams: {
  document_id: string;
};
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: DocumentProcessingStatusResponse;
  400: ProblemResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  409: ProblemResponse;
  413: ProblemResponse;
  422: ProblemResponse;
  429: ProblemResponse;
  503: ProblemResponse;
};
  successResponse: DocumentProcessingStatusResponse;
}

export interface CreateUploadApiV1IngestionUploadsPostOperation {
  method: "post";
  path: "/api/v1/ingestion/uploads";
  pathParams: never;
  queryParams: {
  space_id?: string | null;
};
  requestBody: Body_create_upload_api_v1_ingestion_uploads_post;
  requestContentType: "multipart/form-data";
  responses: {
  201: UploadDocumentResponse;
  400: ProblemResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  409: ProblemResponse;
  413: ProblemResponse;
  422: ProblemResponse;
  429: ProblemResponse;
  503: ProblemResponse;
};
  successResponse: UploadDocumentResponse;
}

export interface ReadDocumentGraphApiV1KnowledgeGraphDocumentsDocumentIdGetOperation {
  method: "get";
  path: "/api/v1/knowledge-graph/documents/{document_id}";
  pathParams: {
  document_id: string;
};
  queryParams: {
  limit?: number;
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: GraphResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: GraphResponse;
}

export interface ReadEntitySubgraphApiV1KnowledgeGraphEntitiesEntityIdSubgraphGetOperation {
  method: "get";
  path: "/api/v1/knowledge-graph/entities/{entity_id}/subgraph";
  pathParams: {
  entity_id: string;
};
  queryParams: {
  depth?: number;
  limit?: number;
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: GraphResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: GraphResponse;
}

export interface ReadPinnedFactsApiV1PinnedFactsGetOperation {
  method: "get";
  path: "/api/v1/pinned-facts";
  pathParams: never;
  queryParams: {
  name?: string | null;
  status?: string | null;
  created_by?: string | null;
  updated_by?: string | null;
  created_date?: string | null;
  updated_date?: string | null;
  sort_key?: "name" | "status" | "created_by" | "updated_by" | "created_at" | "updated_at";
  descending?: boolean;
  page?: number;
  page_size?: number;
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: PinnedFactListResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: PinnedFactListResponse;
}

export interface PostPinnedFactApiV1PinnedFactsPostOperation {
  method: "post";
  path: "/api/v1/pinned-facts";
  pathParams: never;
  queryParams: {
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: PinnedFactCreateRequest;
  requestContentType: "application/json";
  responses: {
  200: PinnedFactDetail;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: PinnedFactDetail;
}

export interface ReadPinnedFactCandidateDetailApiV1PinnedFactsCandidatesCandidateIdGetOperation {
  method: "get";
  path: "/api/v1/pinned-facts/candidates/{candidate_id}";
  pathParams: {
  candidate_id: string;
};
  queryParams: {
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: PinnedFactCandidate;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: PinnedFactCandidate;
}

export interface PostAcceptPinnedFactCandidateApiV1PinnedFactsCandidatesCandidateIdAcceptPostOperation {
  method: "post";
  path: "/api/v1/pinned-facts/candidates/{candidate_id}/accept";
  pathParams: {
  candidate_id: string;
};
  queryParams: {
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: AcceptPinnedFactCandidateRequest;
  requestContentType: "application/json";
  responses: {
  200: PinnedFactDetail;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: PinnedFactDetail;
}

export interface PostRejectPinnedFactCandidateApiV1PinnedFactsCandidatesCandidateIdRejectPostOperation {
  method: "post";
  path: "/api/v1/pinned-facts/candidates/{candidate_id}/reject";
  pathParams: {
  candidate_id: string;
};
  queryParams: {
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: RejectPinnedFactCandidateRequest;
  requestContentType: "application/json";
  responses: {
  200: PinnedFactCandidate;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: PinnedFactCandidate;
}

export interface PostPinnedFactDetectPreviewApiV1PinnedFactsDetectPreviewPostOperation {
  method: "post";
  path: "/api/v1/pinned-facts/detect-preview";
  pathParams: never;
  queryParams: {
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: PinnedFactDetectionPreviewRequest;
  requestContentType: "application/json";
  responses: {
  200: PinnedFactDetectionPreviewResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: PinnedFactDetectionPreviewResponse;
}

export interface ReadPinnedFactDetailApiV1PinnedFactsFactIdGetOperation {
  method: "get";
  path: "/api/v1/pinned-facts/{fact_id}";
  pathParams: {
  fact_id: string;
};
  queryParams: {
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: PinnedFactDetail;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: PinnedFactDetail;
}

export interface PatchPinnedFactApiV1PinnedFactsFactIdPatchOperation {
  method: "patch";
  path: "/api/v1/pinned-facts/{fact_id}";
  pathParams: {
  fact_id: string;
};
  queryParams: {
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: PinnedFactUpdateRequest;
  requestContentType: "application/json";
  responses: {
  200: PinnedFactDetail;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: PinnedFactDetail;
}

export interface ReadPinnedFactCandidatesApiV1PinnedFactsFactIdCandidatesGetOperation {
  method: "get";
  path: "/api/v1/pinned-facts/{fact_id}/candidates";
  pathParams: {
  fact_id: string;
};
  queryParams: {
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: PinnedFactCandidateListResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: PinnedFactCandidateListResponse;
}

export interface ReadPinnedFactHistoryApiV1PinnedFactsFactIdHistoryGetOperation {
  method: "get";
  path: "/api/v1/pinned-facts/{fact_id}/history";
  pathParams: {
  fact_id: string;
};
  queryParams: {
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: PinnedFactHistoryResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: PinnedFactHistoryResponse;
}

export interface PostRevertPinnedFactHistoryApiV1PinnedFactsFactIdHistoryHistoryIdRevertPostOperation {
  method: "post";
  path: "/api/v1/pinned-facts/{fact_id}/history/{history_id}/revert";
  pathParams: {
  fact_id: string;
  history_id: string;
};
  queryParams: {
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: PinnedFactDetail;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: PinnedFactDetail;
}

export interface PostRecheckPinnedFactApiV1PinnedFactsFactIdRecheckPostOperation {
  method: "post";
  path: "/api/v1/pinned-facts/{fact_id}/recheck";
  pathParams: {
  fact_id: string;
};
  queryParams: {
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: PinnedFactDetail;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: PinnedFactDetail;
}

export interface ReadSearchResultsApiV1SearchGetOperation {
  method: "get";
  path: "/api/v1/search";
  pathParams: never;
  queryParams: {
  q: string;
  mode?: SearchMode;
  document_id?: string | null;
  file_type?: string | null;
  entity_type?: string | null;
  page?: number;
  page_size?: number;
  space_id?: string | null;
  all_spaces?: boolean;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: SearchResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: SearchResponse;
}

export interface ReadSpacesApiV1SpacesGetOperation {
  method: "get";
  path: "/api/v1/spaces";
  pathParams: never;
  queryParams: {
  include_archived?: boolean;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: SpaceListResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: SpaceListResponse;
}

export interface PostSpaceApiV1SpacesPostOperation {
  method: "post";
  path: "/api/v1/spaces";
  pathParams: never;
  queryParams: never;
  requestBody: SpaceCreateRequest;
  requestContentType: "application/json";
  responses: {
  201: SpaceResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: SpaceResponse;
}

export interface DeleteSpaceApiV1SpacesSpaceIdDeleteOperation {
  method: "delete";
  path: "/api/v1/spaces/{space_id}";
  pathParams: {
  space_id: string;
};
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: SpaceResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: SpaceResponse;
}

export interface ReadSpaceApiV1SpacesSpaceIdGetOperation {
  method: "get";
  path: "/api/v1/spaces/{space_id}";
  pathParams: {
  space_id: string;
};
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: SpaceResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: SpaceResponse;
}

export interface PatchSpaceApiV1SpacesSpaceIdPatchOperation {
  method: "patch";
  path: "/api/v1/spaces/{space_id}";
  pathParams: {
  space_id: string;
};
  queryParams: never;
  requestBody: SpaceUpdateRequest;
  requestContentType: "application/json";
  responses: {
  200: SpaceResponse;
  401: ProblemResponse;
  404: ProblemResponse;
  422: ProblemResponse;
};
  successResponse: SpaceResponse;
}

export interface ReadMyUsageApiV1UsageMeGetOperation {
  method: "get";
  path: "/api/v1/usage/me";
  pathParams: never;
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: UsageSummaryResponse;
  401: ProblemResponse;
};
  successResponse: UsageSummaryResponse;
}

export interface HealthLivenessHealthGetOperation {
  method: "get";
  path: "/health";
  pathParams: never;
  queryParams: never;
  requestBody: never;
  requestContentType: never;
  responses: {
  200: LivenessResponse;
};
  successResponse: LivenessResponse;
}

export interface RuntimeStatusStatusGetOperation {
  method: "get";
  path: "/status";
  pathParams: never;
  queryParams: {
  type?: string | null;
};
  requestBody: never;
  requestContentType: never;
  responses: {
  200: unknown;
  422: HTTPValidationError;
};
  successResponse: unknown;
}
